version: '3'
services:
  db: 
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - my-datavolume:/var/lib/mysql

  www:
    image: php:apache
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

volumes:
  my-datavolume:
